name: flutter_dialog_manager
description: A Flutter package that allows for neater declaration, abstraction and use of customisable dialogs.
version: 1.0.0
homepage: https://github.com/Crazelu/dialog-manager

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: